apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    namespace: mvs-pipeline
    name: nexus
  spec:
    type: NodePort
    ports:
    - name: 'nexus'
      port: 8082
      targetPort: 8081
    - name: 'docker'
      port: 5000
      targetPort: 5000
    selector:
      app: nexus

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    namespace: mvs-pipeline
    labels:
      app: nexus
    name: nexus
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        labels:
          app: nexus
      spec:
        containers:
        - image: registry.sbx.zone/sonatype/nexus3:latest
          name: nexus
          imagePullPolicy: Always
          resources: {}
          stdin: true
          tty: true

kind: List
metadata: {}


