apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    namespace: mvs-pipeline
    name: sonarqube
  spec:
    type: NodePort
    ports:
    - name: 'sonarqube'
      port: 9000
      targetPort: 9000
    selector:
      app: sonarqube

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    namespace: mvs-pipeline
    labels:
      app: sonarqube
    name: sonarqube
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        labels:
          app: sonarqube
      spec:
        containers:
        - image: registry.sbx.zone/sonarqube:6.7-alpine
          name: sonarqube
          imagePullPolicy: Always
          resources: {}
          stdin: true
          tty: true 

kind: List
metadata: {}


