apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    namespace: mvs-pipeline
    name: jenkins
  spec:
    type: NodePort
    ports:
    - name: 'jenkins'
      port: 8080
      targetPort: 8080
    selector:
      app: jenkins

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    namespace: mvs-pipeline
    labels:
      app: jenkins
    name: jenkins
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        labels:
          app: jenkins
      spec:
        containers:
        - image: registry.sbx.zone/mvs/jenkins:latest
          name: jenkins
          imagePullPolicy: Always
          resources: {}
          stdin: true
          tty: true

kind: List
metadata: {}
