apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    namespace: mvs-pipeline
    name: jira
  spec:
    type: NodePort
    ports:
    - name: 'jira'
      port: 8081
      targetPort: 8080
    selector:
      app: jira

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    namespace: mvs-pipeline
    labels:
      app: jira
    name: jira
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        labels:
          app: jira
      spec:
        containers:
        - image: registry.sbx.zone/mvs/jira:latest
          name: jira
          imagePullPolicy: Always
          resources: {}
          stdin: true
          tty: true

kind: List
metadata: {}